# Generated by Django 3.1.3 on 2020-11-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.IntegerField()),
                ('rate_car_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsapp.car')),
            ],
        ),
    ]
